export const SLIDER_LIST_REQUEST = "SLIDER_LIST_REQUEST";
export const SLIDER_LIST_SUCCESS = "SLIDER_LIST_SUCCESS";
export const SLIDER_LIST_FAIL = "SLIDER_LIST_FAIL";

export const SLIDER_DELETE_REQUEST = "SLIDER_DELETE_REQUEST";
export const SLIDER_DELETE_SUCCESS = "SLIDER_DELETE_SUCCESS";
export const SLIDER_DELETE_FAIL = "SLIDER_DELETE_FAIL";


export const SLIDER_EDIT_REQUEST = "SLIDER_EDIT_REQUEST";
export const SLIDER_EDIT_SUCCESS = "SLIDER_EDIT_SUCCESS";
export const SLIDER_EDIT_FAIL = "SLIDER_EDIT_FAIL";

export const SLIDER_CREATE_REQUEST = "SLIDER_CREATE_REQUEST";
export const SLIDER_CREATE_SUCCESS = "SLIDER_CREATE_SUCCESS";
export const SLIDER_CREATE_FAIL = "SLIDER_CREATE_FAIL";
export const SLIDER_CREATE_RESET = "SLIDER_CREATE_RESET";